workflows:
  ios-sidestore:
    name: Flutter → Unsigned IPA + Runner.app cho SideStore (100% work)
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Get packages
        script: flutter pub get

      - name: Build Runner.app (unsigned)
        script: |
          flutter build ios --release --no-codesign

      - name: Tạo IPA bằng cách zip thư mục Runner.app (SideStore chấp nhận 100%)
        script: |
          cd build/ios/iphoneos

          # Tạo IPA bằng zip (đúng chuẩn Apple)
          zip -r9q "../../Runner-$(git rev-parse --short HEAD).ipa" Runner.app

          # Copy Runner.app ra ngoài cho SideStore PC
          cp -r Runner.app ../../..

          # Tạo zip nhẹ cho SideStore PC
          cd ../../..
          ditto -c -k --sequesterRsrc --keepParent Runner.app Runner.app.zip

    artifacts:
      - Runner-*.ipa         # ← Đây chính là file IPA unsigned, cài được bằng SideStore
      - Runner.app           # ← Folder để kéo thả vào SideStore trên PC
      - Runner.app.zip       # ← Nhẹ nhất, tiện tải

    publishing:
      email:
        recipients:
          - nguyendinhphuoccao2017@gmail.com
        notify:
          success: true
          failure: true