workflows:
  ios-sidestore:
    name: Flutter → Unsigned IPA + Runner.app for SideStore
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest

    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: '**'
          include: true
          source: true

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Flutter build iOS (no code signing)
        script: |
          flutter build ios --release --no-codesign

      - name: Create fake ExportOptions.plist (bắt buộc phải có file này dù không ký)
        script: |
          cat > "$FCI_BUILD_DIR/exportOptions.plist" <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>compileBitcode</key>
              <false/>
              <key>thinning</key>
              <string><none/></string>
          </dict>
          </plist>
          EOF

      - name: Archive bằng xcodebuild với tắt hoàn toàn code signing (Xcode 16+ vẫn chấp nhận)
        script: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -sdk iphoneos \
                     -archivePath "$FCI_BUILD_DIR/Runner.xcarchive" \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGN_ENTITLEMENTS="" \
                     CODE_SIGNING_IDENTITY="" \
                     archive

      - name: Export IPA (unsigned)
        script: |
          xcodebuild -exportArchive \
                     -archivePath "$FCI_BUILD_DIR/Runner.xcarchive" \
                     -exportPath "$FCI_BUILD_DIR/ipa" \
                     -exportOptionsPlist "$FCI_BUILD_DIR/exportOptions.plist"

      - name: Copy Runner.app ra ngoài + zip
        script: |
          cp -r "$FCI_BUILD_DIR/Runner.xcarchive/Products/Applications/Runner.app" "$FCI_BUILD_DIR/"

          # Đổi tên IPA có commit hash
          COMMIT=$(git rev-parse --short HEAD)
          mv "$FCI_BUILD_DIR/ipa/Runner.ipa" "$FCI_BUILD_DIR/ipa/Runner-${COMMIT}.ipa"

          # Tạo .zip cho SideStore PC
          cd "$FCI_BUILD_DIR"
          ditto -c -k --sequesterRsrc --keepParent Runner.app Runner.app.zip

    artifacts:
      - $FCI_BUILD_DIR/ipa/*.ipa
      - $FCI_BUILD_DIR/Runner.app
      - $FCI_BUILD_DIR/Runner.app.zip

    publishing:
      email:
        recipients:
          - nguyendinhphuoccao2017@gmail.com
        notify:
          success: true
          failure: true