workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    instance_type: mac_mini_m2 

    environment:
      flutter: stable
      xcode: latest
      
    scripts:
    - name: Build Unsigned IPA for SideStore
      script: |
        # 1. Lấy dependencies
        flutter packages get
        
        # 2. Xây dựng Product Archive (Vẫn tắt ký mã)
        xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphoneos \
          -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
          -archivePath build/Runner.xcarchive archive
          
        # 3. Xuất file IPA sử dụng ExportOptions không Provisioning Profile
        # Sử dụng tùy chọn exportOptionsPlist và chỉ định method là development
        # Điều này tạo ra IPA với placeholder signing hoặc minimal signing.
        # Rất quan trọng: Bỏ cờ -allowProvisioningUpdates để tránh việc tự động tìm profile.
        xcodebuild -exportArchive -archivePath build/Runner.xcarchive \
          -exportPath build/ipa_output \
          -exportOptionsPlist ./codemagic_manual_export_options.plist

    artifacts:
      # Thu thập file .ipa
      - build/ipa_output/Runner.ipa