workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    instance_type: mac_mini_m2 

    environment:
      flutter: stable
      xcode: latest
      
    scripts:
      # Lệnh này BẮT BUỘC phải có để build
      - name: Build iOS Simulator
        script: |
          flutter packages get
          flutter build ios --no-codesign
          
    artifacts:
      # Lệnh này BẮT BUỘC phải có để Codemagic thu thập file
      - build/ios/iphoneos/Runner.app 
      
 