workflows:
  ios-sidestore:
    name: Flutter → Unsigned IPA + Runner.app cho SideStore
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Get packages
        script: flutter pub get

      - name: Build IPA unsigned + lấy .app (một lệnh duy nhất)
        script: |
          # Lệnh thần thánh – Flutter tự làm hết, không cần xcodebuild archive/export
          flutter build ipa --release --no-codesign

          # Copy Runner.app ra thư mục gốc để dùng với SideStore PC
          cp -r build/ios/iphoneos/Runner.app .

          # Đổi tên IPA cho đẹp (có commit hash)
          COMMIT=$(git rev-parse --short HEAD)
          mv build/ios/ipa/*.ipa "Runner-${COMMIT}.ipa"

          # Tạo zip nhẹ
          ditto -c -k --sequesterRsrc --keepParent Runner.app Runner.app.zip

    artifacts:
      - Runner-*.ipa        # IPA unsigned → cài bằng SideStore/AltStore/TrollStore
      - Runner.app          # folder .app → kéo thả vào SideStore PC (Win/Mac/Linux)
      - Runner.app.zip      # bản nén nhẹ nhất

    publishing:
      email:
        recipients:
          - nguyendinhphuoccao2017@gmail.com
        notify:
          success: true
          failure: true